# Generated by Django 5.2.13 on 2026-09-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Student ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Telegram ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=150, verbose_name="F.I.SH"),
                ),
                (
                    "streak",
                    models.IntegerField(default=0, verbose_name="Ketma-ket kunlar"),
                ),
                (
                    "words_learned",
                    models.IntegerField(default=0, verbose_name="Yodlangan so'zlar"),
                ),
                (
                    "tests_completed",
                    models.IntegerField(default=0, verbose_name="Yechilgan testlar"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "O'quvchi",
                "verbose_name_plural": "O'quvchilar",
            },
        ),
        migrations.CreateModel(
            name="Vocabulary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "korean",
                    models.CharField(max_length=100, verbose_name="Koreyscha so'z"),
                ),
                (
                    "translation",
                    models.CharField(
                        max_length=200, verbose_name="O'zbekcha tarjimasi"
                    ),
                ),
                (
                    "level",
                    models.IntegerField(default=1, verbose_name="TOPIK Daraja (1-6)"),
                ),
            ],
            options={
                "verbose_name": "Lug'at so'zi",
                "verbose_name_plural": "Lug'at",
            },
        ),
    ]
