# Generated by Django 5.2.13 on 2026-09-19 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Imtihon nomi"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Tavsif"),
                ),
                (
                    "level",
                    models.IntegerField(default=1, verbose_name="TOPIK Daraja (1-6)"),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(default=20, verbose_name="Vaqt (daqiqa)"),
                ),
                (
                    "pass_score",
                    models.IntegerField(default=60, verbose_name="O'tish bali (%)"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Faolmi?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "TOPIK Imtihon",
                "verbose_name_plural": "TOPIK Imtihonlari",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="last_active_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Oxirgi faollik kuni"
            ),
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Savol matni / Matn")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("reading", "O'qish (Reading)"),
                            ("listening", "Eshitish (Listening)"),
                            ("grammar", "Grammatika"),
                            ("vocabulary", "Lug'at"),
                        ],
                        default="reading",
                        max_length=20,
                        verbose_name="Savol turi",
                    ),
                ),
                (
                    "option_a",
                    models.CharField(max_length=255, verbose_name="A variant"),
                ),
                (
                    "option_b",
                    models.CharField(max_length=255, verbose_name="B variant"),
                ),
                (
                    "option_c",
                    models.CharField(max_length=255, verbose_name="C variant"),
                ),
                (
                    "option_d",
                    models.CharField(max_length=255, verbose_name="D variant"),
                ),
                (
                    "correct_option",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        verbose_name="To'g'ri javob",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Tushuntirish / Izoh (AI Tutor)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Tartib raqami"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="bot_app.exam",
                        verbose_name="Imtihon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imtihon savoli",
                "verbose_name_plural": "Imtihon savollari",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_questions",
                    models.IntegerField(default=0, verbose_name="Jami savollar"),
                ),
                (
                    "correct_answers",
                    models.IntegerField(default=0, verbose_name="To'g'ri javoblar"),
                ),
                (
                    "score_percentage",
                    models.FloatField(default=0.0, verbose_name="Ball foizi (%)"),
                ),
                ("passed", models.BooleanField(default=False, verbose_name="O'tdimi?")),
                (
                    "answers_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Berilgan javoblar"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tugatilgan vaqti"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="bot_app.exam",
                        verbose_name="Imtihon",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_results",
                        to="bot_app.student",
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imtihon natijasi",
                "verbose_name_plural": "Imtihon natijalari",
                "ordering": ["-completed_at"],
            },
        ),
    ]
