# Generated by Django 5.2.13 on 2026-09-21 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_app", "0002_exam_student_last_active_date_examquestion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Guruh nomi")),
                (
                    "book_level",
                    models.CharField(
                        choices=[
                            ("1A", "1A"),
                            ("1B", "1B"),
                            ("2A", "2A"),
                            ("2B", "2B"),
                        ],
                        max_length=2,
                        verbose_name="Kitob bosqichi",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Izoh")),
            ],
            options={
                "verbose_name": "Guruh",
                "verbose_name_plural": "Guruhlar",
                "ordering": ["book_level", "name"],
            },
        ),
        migrations.AddField(
            model_name="student",
            name="book_level",
            field=models.CharField(
                choices=[("1A", "1A"), ("1B", "1B"), ("2A", "2A"), ("2B", "2B")],
                default="1A",
                max_length=2,
                verbose_name="Kitob bosqichi",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Faol"),
        ),
        migrations.AddField(
            model_name="student",
            name="teacher_notes",
            field=models.TextField(blank=True, verbose_name="Ustoz qaydlari"),
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=4000, verbose_name="Xabar matni")),
                (
                    "audience",
                    models.CharField(max_length=255, verbose_name="Qabul qiluvchilar"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yuborilgan vaqt"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yuborgan ustoz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xabar",
                "verbose_name_plural": "Xabarlar tarixi",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_level",
                    models.CharField(
                        choices=[
                            ("1A", "1A"),
                            ("1B", "1B"),
                            ("2A", "2A"),
                            ("2B", "2B"),
                        ],
                        max_length=2,
                        verbose_name="Kitob bosqichi",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Dars raqami")),
                ("title", models.CharField(max_length=200, verbose_name="Mavzu")),
            ],
            options={
                "verbose_name": "Dars",
                "verbose_name_plural": "Darslar",
                "ordering": ["book_level", "number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("book_level", "number"), name="unique_book_lesson"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Grammar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Qoida")),
                ("explanation", models.TextField(verbose_name="O‘zbekcha izoh")),
                ("examples", models.TextField(blank=True, verbose_name="Misollar")),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Tartib"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grammar",
                        to="bot_app.lesson",
                        verbose_name="Dars",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grammatika qoidasi",
                "verbose_name_plural": "Grammatika",
                "ordering": ["lesson", "order"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exams",
                to="bot_app.lesson",
                verbose_name="Dars",
            ),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="words",
                to="bot_app.lesson",
                verbose_name="Dars",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="bot_app.studygroup",
                verbose_name="Guruh",
            ),
        ),
        migrations.CreateModel(
            name="StudentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Saytda o‘qilgan vaqt"
                    ),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="bot_app.announcement",
                        verbose_name="Xabar",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="bot_app.student",
                        verbose_name="O‘quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xabar oluvchi",
                "verbose_name_plural": "Xabar oluvchilar",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("announcement", "student"),
                        name="unique_message_student",
                    )
                ],
            },
        ),
    ]
