# Generated by Django 5.2.13 on 2026-09-21 09:51

import django.db.models.deletion
from django.db import migrations, models


def align_groups(apps, schema_editor):
    Group = apps.get_model("bot_app", "StudyGroup")
    Student = apps.get_model("bot_app", "Student")
    for level in ("1A", "1B", "2A", "2B"):
        groups = list(Group.objects.filter(book_level=level).order_by("pk"))
        if groups:
            group = groups[0]
            for duplicate in groups[1:]:
                Student.objects.filter(group=duplicate).update(group=group)
                group.notes += "\n" + duplicate.name + ": " + duplicate.notes
                duplicate.delete()
            group.save()
        else:
            group = Group.objects.create(book_level=level, name=f"{level} guruhi")
        Student.objects.filter(book_level=level).update(group=group)


class Migration(migrations.Migration):

    dependencies = [
        ("bot_app", "0003_studygroup_student_book_level_student_is_active_and_more"),
    ]

    operations = [
        migrations.RunPython(align_groups, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="vocabulary",
            options={
                "ordering": ["lesson", "order", "id"],
                "verbose_name": "Lug'at so'zi",
                "verbose_name_plural": "Lug'at",
            },
        ),
        migrations.AddField(
            model_name="grammar",
            name="source_key",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Manba kaliti",
            ),
        ),
        migrations.AddField(
            model_name="grammar",
            name="source_page",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="PDF sahifasi"
            ),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="order",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Darsdagi tartib"
            ),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="source_key",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Manba kaliti",
            ),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="source_page",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, verbose_name="PDF sahifasi"
            ),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="book_level",
            field=models.CharField(
                choices=[("1A", "1A"), ("1B", "1B"), ("2A", "2A"), ("2B", "2B")],
                max_length=2,
                unique=True,
                verbose_name="Kitob bosqichi",
            ),
        ),
        migrations.CreateModel(
            name="GrammarProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="O‘qilgan vaqt"),
                ),
                (
                    "grammar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="bot_app.grammar",
                        verbose_name="Qoida",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grammar_progress",
                        to="bot_app.student",
                        verbose_name="O‘quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "O‘qilgan grammatika",
                "verbose_name_plural": "O‘qilgan grammatika qoidalari",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "grammar"), name="unique_student_grammar"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WordProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learned",
                    models.BooleanField(default=False, verbose_name="Yodlangan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Oxirgi mashq"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_progress",
                        to="bot_app.student",
                        verbose_name="O‘quvchi",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="bot_app.vocabulary",
                        verbose_name="So‘z",
                    ),
                ),
            ],
            options={
                "verbose_name": "So‘z o‘rganish natijasi",
                "verbose_name_plural": "So‘z o‘rganish natijalari",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "word"), name="unique_student_word"
                    )
                ],
            },
        ),
    ]
