# Generated by Django 5.2.13 on 2026-09-21 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_app", "0004_alter_vocabulary_options_grammar_source_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrammarExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "sentence",
                    models.CharField(
                        max_length=500, verbose_name="Bo‘sh joyli gap (___)"
                    ),
                ),
                (
                    "translation",
                    models.CharField(
                        max_length=500, verbose_name="Gapning o‘zbekcha ma’nosi"
                    ),
                ),
                (
                    "options",
                    models.JSONField(verbose_name="Javob variantlari (ro‘yxat)"),
                ),
                (
                    "correct_index",
                    models.PositiveSmallIntegerField(
                        verbose_name="To‘g‘ri variant indeksi (0 dan)"
                    ),
                ),
                ("explanation", models.TextField(verbose_name="Javob izohi")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "grammar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exercises",
                        to="bot_app.grammar",
                        verbose_name="Qoida va dars",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grammatika mashqi",
                "verbose_name_plural": "Grammatika mashqlari",
            },
        ),
        migrations.CreateModel(
            name="PracticeAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "book_level",
                    models.CharField(
                        choices=[
                            ("1A", "1A"),
                            ("1B", "1B"),
                            ("2A", "2A"),
                            ("2B", "2B"),
                        ],
                        max_length=2,
                        verbose_name="Kitob bosqichi",
                    ),
                ),
                (
                    "questions",
                    models.JSONField(default=list, verbose_name="Savollar nusxasi"),
                ),
                ("answers", models.JSONField(default=dict, verbose_name="Javoblar")),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="To‘g‘ri javoblar"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tugatilgan vaqt"
                    ),
                ),
                (
                    "ai_analysis",
                    models.TextField(blank=True, verbose_name="AI tavsiyasi"),
                ),
                (
                    "ai_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="AI modeli"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_attempts",
                        to="bot_app.student",
                        verbose_name="O‘quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grammatika mashqi natijasi",
                "verbose_name_plural": "Grammatika mashqi natijalari",
                "ordering": ["-created_at"],
            },
        ),
    ]
